pipeline {
    agent {
        kubernetes {
            yaml '''
              apiVersion: v1
              kind: Pod
              spec:
                containers:
                - name: maven
                  image: maven:3.9.9-eclipse-temurin-17
                  command:
                  - cat
                  tty: true
                - name: docker
                  image: docker:dind
                  command:
                  - cat
                  tty: true
            '''
        }
    }
    stages {
        stage('Build') {
            steps {
                container('maven') {
                    sh 'mvn -B -DskipTests clean package';
                }
            }
        }
        stage('Test') {
            steps {
                container('maven') {
                    sh 'mvn test';
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml';
                }
            }
        }
        stage('Deliver') { 
            steps {
                container('maven') {
                    sh './jenkins/scripts/deliver.sh';
                }
            }
        }
        stage('Docker') { 
            steps {
                container('docker') {
                    sh 'docker ps';
                }
            }
        }
    }
}
