pipeline {
    agent {
        kubernetes {
            containerTemplate {
                name 'maven'
                image 'maven:3.9.12-sapmachine-21'
                command 'sleep'
                args '9999999'
            }
            containerTemplate {
                name 'docker'
                image 'docker:dind'
            }
        }
    }
    stages {
        stage('Build') {
            steps {
                container('maven') {
                    sh 'mvn -B -DskipTests clean package';
                }
            }
        }
        stage('Test') {
            steps {
                container('maven') {
                    sh 'mvn test';
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml';
                }
            }
        }
        stage('Deliver') { 
            steps {
                container('maven') {
                    sh './jenkins/scripts/deliver.sh';
                }
            }
        }
        stage('Docker') { 
            steps {
                container('docker') {
                    sh 'docker ps';
                }
            }
        }
    }
}
